# Preface {.unnumbered}

This section discusses why these notes exist.
Students may skip this section.

## Why publish a new set of Linear Algebra notes?

Linear Algebra, like Calculus, is one of the math subjects with the most textbooks, so it's reasonable to ask why a new set of notes is needed.
Plainly, I looked at the six open-access books on the subject on the AIMath website and found that none of them were fit for my purpose (detailed below).

## The perspective of these notes

These notes are constructed to vindicate the following objectives:

1.  
    It is morally right for course materials to be free.
    Few existing books on this subject in English satisfy this criterion (eg @hefferon is GFDL or CC BY-SA 3.0 US, @treil is  CC BY-NC-ND 3.0 with source unavailable). 
    This book, and the source used to generate it are freely available with a permissive license.

1.  
    In practice, scientists, engineers, etc. need to be able to recognize linearity so that they may choose the correct solution techniques. 
    They also need to understand why linear problems are preferable to non-linear ones so that they might try to massage their current problem into a linear one.

1.  
    When we say "solution techniques" as above, 99% of the time we mean software packages.
    Mathematicians and physicists teach linear algebra techniques in colleges and universities, and emphasize by-hand solution techniques for historical and cultural reasons. 
    Most working people who encounter such problems do not use such techniques, they recognize that their problem is linear and offload the problem to a software package. 
    Mathematicians and physicists generally get a second pass at learning linear algebra in a more theory-heavy context (at the very least when learning modules), and so do not need that approach in a first course.

1. 
    The usefulness of linear algebra techniques stems wholly from the homomorphism property of linear maps: 

    $$ L(a V + b W) = a L(V) + b L(W) $$ 

    No introductory, open-access, English language books on the topic that I am aware of motivate the study of the subject with this point. 
    They traditionally begin with coordinate geometry or solving systems of linear equations. 
    It is a very mathematicians' way of thinking to motivate study of a topic by identifying a class of equations and asking "How do we solve them? What properties do they have?" 
    This is not a way of thinking that is useful for people encountering linearity in the wild. 
    
    Many advanced undergraduate books like @axler begin with the definition of a vector space.
    It is also a very mathematician's way of thinking to begin with a definition of a set of objects which will be mapped into or out of (viz. most treatments of Abstract Algebra).
    To talk about maps (which are really the objects of interest), *surely* we must first talk about (co)domains!

    Coordinate geometry is, at least, a class of real problems where linear techniques naturally arise, but the relevance of this as an example from "the wild" has basically vanished in the last 70 years.
    Today's scientists and engineers are more likely to encounter linearity in optimization, data science, machine learning, or numerical PDEs.

So, for these reasons, I set out to write my own course notes.