from r-base

run apt-get -y update && apt-get -y install libblas3 liblapack3 liblapack-dev libblas-dev 
run apt-get -y update && apt-get -y install gfortran
run apt-get -y update && apt-get -y install cmake

entrypoint [ "/usr/bin/bash" ]